export const skills = [
  { skill: 'HTML' },
  { skill: 'CSS' },
  { skill: 'JavaScript' },
  { skill: 'TypeScript' },
  { skill: 'Angular' },
  { skill: 'React' },
  { skill: 'Next.js' },
  { skill: 'Chakra UI' },
  { skill: 'Tailwind CSS' },
  { skill: 'Bootstrap' },
  { skill: 'Node js' },
  { skill: 'MongoDB' },
  { skill: 'SQL' },
  { skill: 'Git' },
  { skill: 'Rest API' },
];
